version: '3.9'
services:
  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: supernova
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=example

volumes:
  db:
  redis: